package online_book_sales;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 * @author Ömer Faruk Akçay
 */
public class Details_screen extends javax.swing.JFrame {
    JFrame Screen;
    int kitapID;
    public Details_screen(JFrame Screen, int kitapID) throws SQLException {
        this.Screen = Screen;
        this.kitapID = kitapID;
        initComponents();
        
        List list = new List();
        
        ArrayList<Kitap> kitaplar = list.getKitaplar(kitapID);
        if (kitaplar.isEmpty()) {
            System.out.println("Kitap bulunamadı.");
        } else {
            for (Kitap kitap : kitaplar) {
                lblBosKitapAdi.setText(kitap.getKitapAdi());
                lblBosTur.setText(kitap.getTur());
                lblBosSayfaSayisi.setText(String.valueOf(kitap.getSayfaSayisi()));
                lblBosFiyat.setText(String.valueOf(kitap.getFiyat()));
                lblBosStok.setText(String.valueOf(kitap.getStokAdedi()));
                lblBosYazarAdi.setText(kitap.getYazarAdi());
                lblBosYazarSoyadi.setText(kitap.getYazarSoyadi());
                lblBosYayinevi.setText(kitap.getYayineviAdi());
                lblBosSatici.setText(String.valueOf(kitap.getSaticiID()));

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCikis = new javax.swing.JButton();
        lblHosgeldin = new javax.swing.JLabel();
        btnProfil = new javax.swing.JButton();
        btnGeri = new javax.swing.JButton();
        lblKitapAdi = new javax.swing.JLabel();
        lblBosKitapAdi = new javax.swing.JLabel();
        lblYazarAdi = new javax.swing.JLabel();
        lblBosYazarAdi = new javax.swing.JLabel();
        lblBosYazarSoyadi = new javax.swing.JLabel();
        lblYazarSoyadi = new javax.swing.JLabel();
        LblYayinevi = new javax.swing.JLabel();
        lblBosYayinevi = new javax.swing.JLabel();
        lblBosTur = new javax.swing.JLabel();
        lblTur = new javax.swing.JLabel();
        lblSayfaSayisi = new javax.swing.JLabel();
        lblBosSayfaSayisi = new javax.swing.JLabel();
        lblSatici = new javax.swing.JLabel();
        lblBosSatici = new javax.swing.JLabel();
        lblFiyat = new javax.swing.JLabel();
        lblBosFiyat = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        lblBosStok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 450));

        btnCikis.setBackground(new java.awt.Color(255, 51, 51));
        btnCikis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCikis.setForeground(new java.awt.Color(255, 255, 255));
        btnCikis.setText("Çıkış");
        btnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisActionPerformed(evt);
            }
        });

        lblHosgeldin.setBackground(new java.awt.Color(204, 255, 255));
        lblHosgeldin.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblHosgeldin.setText("Kitap Detayı");
        lblHosgeldin.setPreferredSize(new java.awt.Dimension(150, 25));

        btnProfil.setBackground(new java.awt.Color(0, 153, 0));
        btnProfil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProfil.setForeground(new java.awt.Color(255, 255, 255));
        btnProfil.setText("Profil");
        btnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilActionPerformed(evt);
            }
        });

        btnGeri.setBackground(new java.awt.Color(255, 51, 51));
        btnGeri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGeri.setForeground(new java.awt.Color(255, 255, 255));
        btnGeri.setText("Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        lblKitapAdi.setBackground(new java.awt.Color(204, 255, 255));
        lblKitapAdi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKitapAdi.setText("Kitap Adı:");

        lblBosKitapAdi.setBackground(new java.awt.Color(204, 255, 255));
        lblBosKitapAdi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblYazarAdi.setBackground(new java.awt.Color(204, 255, 255));
        lblYazarAdi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblYazarAdi.setText("Yazar Adı:");
        lblYazarAdi.setMaximumSize(new java.awt.Dimension(74, 20));
        lblYazarAdi.setMinimumSize(new java.awt.Dimension(74, 20));

        lblBosYazarAdi.setBackground(new java.awt.Color(204, 255, 255));
        lblBosYazarAdi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBosYazarAdi.setMaximumSize(new java.awt.Dimension(74, 20));
        lblBosYazarAdi.setMinimumSize(new java.awt.Dimension(74, 20));

        lblBosYazarSoyadi.setBackground(new java.awt.Color(204, 255, 255));
        lblBosYazarSoyadi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBosYazarSoyadi.setMaximumSize(new java.awt.Dimension(74, 20));
        lblBosYazarSoyadi.setMinimumSize(new java.awt.Dimension(74, 20));

        lblYazarSoyadi.setBackground(new java.awt.Color(204, 255, 255));
        lblYazarSoyadi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblYazarSoyadi.setText("Yazar Soyadı:");
        lblYazarSoyadi.setMaximumSize(new java.awt.Dimension(74, 20));
        lblYazarSoyadi.setMinimumSize(new java.awt.Dimension(74, 20));

        LblYayinevi.setBackground(new java.awt.Color(204, 255, 255));
        LblYayinevi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblYayinevi.setText("Yayınevi Adı:");

        lblBosYayinevi.setBackground(new java.awt.Color(204, 255, 255));
        lblBosYayinevi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblBosTur.setBackground(new java.awt.Color(204, 255, 255));
        lblBosTur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBosTur.setMaximumSize(new java.awt.Dimension(74, 20));
        lblBosTur.setMinimumSize(new java.awt.Dimension(74, 20));

        lblTur.setBackground(new java.awt.Color(204, 255, 255));
        lblTur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTur.setText("Tür:");
        lblTur.setMaximumSize(new java.awt.Dimension(74, 20));
        lblTur.setMinimumSize(new java.awt.Dimension(74, 20));

        lblSayfaSayisi.setBackground(new java.awt.Color(204, 255, 255));
        lblSayfaSayisi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSayfaSayisi.setText("Sayfa Sayısı:");

        lblBosSayfaSayisi.setBackground(new java.awt.Color(204, 255, 255));
        lblBosSayfaSayisi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblSatici.setBackground(new java.awt.Color(204, 255, 255));
        lblSatici.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSatici.setText("Satıcı ID:");

        lblBosSatici.setBackground(new java.awt.Color(204, 255, 255));
        lblBosSatici.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblFiyat.setBackground(new java.awt.Color(204, 255, 255));
        lblFiyat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFiyat.setText("Fiyat:");

        lblBosFiyat.setBackground(new java.awt.Color(204, 255, 255));
        lblBosFiyat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblStok.setBackground(new java.awt.Color(204, 255, 255));
        lblStok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStok.setText("Stok Adedi:");

        lblBosStok.setBackground(new java.awt.Color(204, 255, 255));
        lblBosStok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnProfil)
                .addGap(342, 342, 342)
                .addComponent(lblHosgeldin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(btnGeri)
                .addGap(18, 18, 18)
                .addComponent(btnCikis)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSayfaSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStok, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBosStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBosTur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBosSayfaSayisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBosFiyat, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblBosKitapAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSatici, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblYayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYazarSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYazarAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBosYazarSoyadi, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblBosYayinevi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBosSatici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBosYazarAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHosgeldin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGeri)
                            .addComponent(btnCikis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addComponent(btnProfil)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYazarAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBosYazarAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYazarSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBosYazarSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblYayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBosYayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBosSatici, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSatici, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBosKitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBosTur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSayfaSayisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBosSayfaSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBosFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBosStok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(154, 154, 154))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisActionPerformed
        // TODO add your handling code here:
        
        Log_in_screen log_in_screen = new Log_in_screen();
        log_in_screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCikisActionPerformed

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfilActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        // TODO add your handling code here:
        this.Screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGeriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblYayinevi;
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnProfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBosFiyat;
    private javax.swing.JLabel lblBosKitapAdi;
    private javax.swing.JLabel lblBosSatici;
    private javax.swing.JLabel lblBosSayfaSayisi;
    private javax.swing.JLabel lblBosStok;
    private javax.swing.JLabel lblBosTur;
    private javax.swing.JLabel lblBosYayinevi;
    private javax.swing.JLabel lblBosYazarAdi;
    private javax.swing.JLabel lblBosYazarSoyadi;
    private javax.swing.JLabel lblFiyat;
    private javax.swing.JLabel lblHosgeldin;
    private javax.swing.JLabel lblKitapAdi;
    private javax.swing.JLabel lblSatici;
    private javax.swing.JLabel lblSayfaSayisi;
    private javax.swing.JLabel lblStok;
    private javax.swing.JLabel lblTur;
    private javax.swing.JLabel lblYazarAdi;
    private javax.swing.JLabel lblYazarSoyadi;
    // End of variables declaration//GEN-END:variables
}
