package online_book_sales;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * @author Omer Faruk
 */
public class Log_in_screen extends javax.swing.JFrame {
    public Log_in_screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGeri2 = new javax.swing.JButton();
        lblUyeMisin = new javax.swing.JLabel();
        btnUyeOl = new javax.swing.JButton();
        tbdKullaniciGiris = new javax.swing.JPanel();
        lblKullaniciAdi = new javax.swing.JLabel();
        lblKullaniciSifre = new javax.swing.JLabel();
        txtKullaniciAdi = new javax.swing.JTextField();
        txtKullaniciSifre = new javax.swing.JPasswordField();
        btnKullaniciGirisYap = new javax.swing.JButton();
        lblUyeOl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 450));

        btnGeri2.setBackground(new java.awt.Color(255, 51, 51));
        btnGeri2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGeri2.setForeground(new java.awt.Color(255, 255, 255));
        btnGeri2.setText("Geri");
        btnGeri2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeri2ActionPerformed(evt);
            }
        });

        lblUyeMisin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUyeMisin.setText("Üye değil misiniz?");

        btnUyeOl.setBackground(new java.awt.Color(0, 153, 0));
        btnUyeOl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUyeOl.setForeground(new java.awt.Color(255, 255, 255));
        btnUyeOl.setText("Üye ol");
        btnUyeOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUyeOlActionPerformed(evt);
            }
        });

        tbdKullaniciGiris.setBackground(new java.awt.Color(204, 255, 255));

        lblKullaniciAdi.setBackground(new java.awt.Color(204, 255, 255));
        lblKullaniciAdi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKullaniciAdi.setText("Kullanıcı Adı:");

        lblKullaniciSifre.setBackground(new java.awt.Color(204, 255, 255));
        lblKullaniciSifre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKullaniciSifre.setText("Şifre:");
        lblKullaniciSifre.setMaximumSize(new java.awt.Dimension(74, 20));
        lblKullaniciSifre.setMinimumSize(new java.awt.Dimension(74, 20));

        txtKullaniciAdi.setBackground(new java.awt.Color(204, 255, 255));
        txtKullaniciAdi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtKullaniciAdi.setPreferredSize(new java.awt.Dimension(74, 20));

        txtKullaniciSifre.setBackground(new java.awt.Color(204, 255, 255));
        txtKullaniciSifre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtKullaniciSifre.setPreferredSize(new java.awt.Dimension(74, 20));
        txtKullaniciSifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKullaniciSifreActionPerformed(evt);
            }
        });

        btnKullaniciGirisYap.setBackground(new java.awt.Color(0, 153, 0));
        btnKullaniciGirisYap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKullaniciGirisYap.setForeground(new java.awt.Color(255, 255, 255));
        btnKullaniciGirisYap.setText("Giriş Yap");
        btnKullaniciGirisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciGirisYapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tbdKullaniciGirisLayout = new javax.swing.GroupLayout(tbdKullaniciGiris);
        tbdKullaniciGiris.setLayout(tbdKullaniciGirisLayout);
        tbdKullaniciGirisLayout.setHorizontalGroup(
            tbdKullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbdKullaniciGirisLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(tbdKullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(tbdKullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbdKullaniciGirisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKullaniciGirisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );
        tbdKullaniciGirisLayout.setVerticalGroup(
            tbdKullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbdKullaniciGirisLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(tbdKullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(tbdKullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnKullaniciGirisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        lblUyeOl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUyeOl.setText("Giriş Yap");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(tbdKullaniciGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblUyeMisin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUyeOl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(lblUyeOl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGeri2)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(43, Short.MAX_VALUE)
                        .addComponent(lblUyeOl)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnGeri2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(tbdKullaniciGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUyeMisin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUyeOl))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKullaniciGirisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciGirisYapActionPerformed
        // TODO add your handling code here:
        List list = new List();
        
         try {
             ArrayList<User> users = list.getKullanicilar();
             boolean flag = false;

             String inputUserName = txtKullaniciAdi.getText();
             String inputPassword = txtKullaniciSifre.getText();

             for (User user : users) {
                 if (user.getUser_name().equals(inputUserName) && user.getPassword().equals(inputPassword)) {
                     flag = true;
                     break;
                 }
             }

            if (flag){
                String user_name = txtKullaniciAdi.getText();
                
                User_main_screen user_main_screen = new User_main_screen(user_name);
                user_main_screen.setVisible(true);
                dispose();
            }
            else{
                txtKullaniciAdi.setText("");
                txtKullaniciSifre.setText("");
                JOptionPane.showMessageDialog(rootPane, "Kullanıcı adı veya şifre hatalı");
            }
        } catch (SQLException exception) {
            
        }
    }//GEN-LAST:event_btnKullaniciGirisYapActionPerformed

    private void btnUyeOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUyeOlActionPerformed
        // TODO add your handling code here:
        Sign_in_screen sign_in_screen = new Sign_in_screen();
        sign_in_screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUyeOlActionPerformed

    private void txtKullaniciSifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKullaniciSifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKullaniciSifreActionPerformed

    private void btnGeri2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeri2ActionPerformed
        // TODO add your handling code here:
        Introduction_screen introduction_screen = new Introduction_screen();
        introduction_screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGeri2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_in_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_in_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_in_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_in_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_in_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnGeri1;
    private javax.swing.JButton btnGeri2;
    private javax.swing.JButton btnKullaniciGirisYap;
    private javax.swing.JButton btnUyeOl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKullaniciAdi;
    private javax.swing.JLabel lblKullaniciSifre;
    private javax.swing.JLabel lblUyeMisin;
    private javax.swing.JLabel lblUyeOl;
    private javax.swing.JPanel tbdKullaniciGiris;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JPasswordField txtKullaniciSifre;
    // End of variables declaration//GEN-END:variables
}
