package online_book_sales;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * @author Omer Faruk
 */
public class Sign_in_screen extends javax.swing.JFrame {
    public Sign_in_screen() {
        initComponents();
    }
    
public void userInsert() throws SQLException {
    Connection connection = null;
    DbHelper dbHelper = new DbHelper();
    PreparedStatement statement = null;
    
    try {
        connection = dbHelper.getConnection();
        
        String username = txtKullaniciKullaniciAdi.getText();
        if (isUsernameTaken(username)) {
            JOptionPane.showMessageDialog(rootPane, "Kullanıcı adı mevcut.");
            return;  
        }

        String sql = "INSERT INTO kitap.kullanıcılar (Ad, Soyad, DogumTarihi, Cinsiyet, Bakiye, KullanıcıAdı, Sifre, TelefonNumarası, Email) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        statement = connection.prepareStatement(sql);

        statement.setString(1, txtKullaniciAd.getText());
        statement.setString(2, txtKullaniciSoyad.getText());
        statement.setString(3, txtKullaniciDogumTarihi.getText());
        statement.setString(4, txtCinsiyet.getText());
        statement.setFloat(5, 0);
        statement.setString(6, username);
        statement.setString(7, new String(txtKullaniciSifre.getPassword()));
        statement.setString(8, txtKullaniciTelNo.getText());
        statement.setString(9, txtKullaniciEmail.getText());

        
        statement.executeUpdate();
        JOptionPane.showMessageDialog(rootPane, "Kayıt olundu.");

        Log_in_screen log_in_screen = new Log_in_screen();
        log_in_screen.setVisible(true);
        dispose();

    } catch (SQLException sqlException) {
        dbHelper.showErrorMessage(sqlException);
    } finally {
        if (statement != null) {
            statement.close();
        }
        if (connection != null) {
            connection.close();
        }
    }
}
private boolean isUsernameTaken(String username) throws SQLException {
    List list = new List();
    ArrayList<User> users = list.getKullanicilar();
    return users.stream().anyMatch(user -> user.getUser_name().equals(username));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblKullaniciAd = new javax.swing.JLabel();
        lblKullaniciSoyad = new javax.swing.JLabel();
        lblKullaniciEmail = new javax.swing.JLabel();
        lblKullaniciKullaniciAdi = new javax.swing.JLabel();
        lblKullaniciSifre = new javax.swing.JLabel();
        txtKullaniciAd = new javax.swing.JTextField();
        txtKullaniciSoyad = new javax.swing.JTextField();
        txtKullaniciKullaniciAdi = new javax.swing.JTextField();
        txtKullaniciEmail = new javax.swing.JTextField();
        txtKullaniciSifre = new javax.swing.JPasswordField();
        btnKullaniciUyeOl = new javax.swing.JButton();
        lblKullaniciTelNo = new javax.swing.JLabel();
        txtKullaniciTelNo = new javax.swing.JTextField();
        lblDogumTarihi = new javax.swing.JLabel();
        lblCinsiyet = new javax.swing.JLabel();
        txtKullaniciDogumTarihi = new javax.swing.JTextField();
        txtCinsiyet = new javax.swing.JTextField();
        btnGeri = new javax.swing.JButton();
        lblUyeOl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 450));

        lblKullaniciAd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKullaniciAd.setText("Ad:");

        lblKullaniciSoyad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKullaniciSoyad.setText("Soyad:");

        lblKullaniciEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKullaniciEmail.setText("E-mail:");

        lblKullaniciKullaniciAdi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKullaniciKullaniciAdi.setText("Kullanıcı Adı:");

        lblKullaniciSifre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKullaniciSifre.setText("Şifre:");

        txtKullaniciAd.setBackground(new java.awt.Color(204, 255, 255));
        txtKullaniciAd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtKullaniciSoyad.setBackground(new java.awt.Color(204, 255, 255));
        txtKullaniciSoyad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtKullaniciKullaniciAdi.setBackground(new java.awt.Color(204, 255, 255));
        txtKullaniciKullaniciAdi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtKullaniciEmail.setBackground(new java.awt.Color(204, 255, 255));
        txtKullaniciEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtKullaniciSifre.setBackground(new java.awt.Color(204, 255, 255));
        txtKullaniciSifre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnKullaniciUyeOl.setBackground(new java.awt.Color(0, 153, 0));
        btnKullaniciUyeOl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKullaniciUyeOl.setForeground(new java.awt.Color(255, 255, 255));
        btnKullaniciUyeOl.setText("Üye Ol");
        btnKullaniciUyeOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciUyeOlActionPerformed(evt);
            }
        });

        lblKullaniciTelNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKullaniciTelNo.setText("Telefon No:");

        txtKullaniciTelNo.setBackground(new java.awt.Color(204, 255, 255));
        txtKullaniciTelNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblDogumTarihi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDogumTarihi.setText("Doğum Tarihi:");

        lblCinsiyet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCinsiyet.setText("Cinsiyet:");

        txtKullaniciDogumTarihi.setBackground(new java.awt.Color(204, 255, 255));
        txtKullaniciDogumTarihi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtCinsiyet.setBackground(new java.awt.Color(204, 255, 255));
        txtCinsiyet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnGeri.setBackground(new java.awt.Color(255, 51, 51));
        btnGeri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGeri.setForeground(new java.awt.Color(255, 255, 255));
        btnGeri.setText("Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        lblUyeOl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUyeOl.setText("Üye Ol");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(btnKullaniciUyeOl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblUyeOl)
                .addGap(456, 456, 456))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKullaniciSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDogumTarihi)
                    .addComponent(lblKullaniciAd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKullaniciDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciAd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKullaniciEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKullaniciTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKullaniciKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnGeri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblUyeOl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKullaniciKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciAd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKullaniciAd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKullaniciSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKullaniciEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKullaniciTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnKullaniciUyeOl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnGeri)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKullaniciUyeOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciUyeOlActionPerformed
        // TODO add your handling code here:
        try {
            userInsert();
        } catch (SQLException exception) {
            
        }
    }//GEN-LAST:event_btnKullaniciUyeOlActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        // TODO add your handling code here:
        Log_in_screen log_in_screen = new Log_in_screen();
        log_in_screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGeriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_in_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_in_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_in_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_in_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_in_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnKullaniciUyeOl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCinsiyet;
    private javax.swing.JLabel lblDogumTarihi;
    private javax.swing.JLabel lblKullaniciAd;
    private javax.swing.JLabel lblKullaniciEmail;
    private javax.swing.JLabel lblKullaniciKullaniciAdi;
    private javax.swing.JLabel lblKullaniciSifre;
    private javax.swing.JLabel lblKullaniciSoyad;
    private javax.swing.JLabel lblKullaniciTelNo;
    private javax.swing.JLabel lblUyeOl;
    private javax.swing.JTextField txtCinsiyet;
    private javax.swing.JTextField txtKullaniciAd;
    private javax.swing.JTextField txtKullaniciDogumTarihi;
    private javax.swing.JTextField txtKullaniciEmail;
    private javax.swing.JTextField txtKullaniciKullaniciAdi;
    private javax.swing.JPasswordField txtKullaniciSifre;
    private javax.swing.JTextField txtKullaniciSoyad;
    private javax.swing.JTextField txtKullaniciTelNo;
    // End of variables declaration//GEN-END:variables
}
